### ISSUE TITLE
visionfive 启动情况追踪

### ISSUE THREAD

**Issue by YdrMaster** [YdrMaster/zCore#3]
OpenSBI+uboot 网络引导可进入内核但报错

```bash
Starting kernel ...

!!!

boot page table launched, sstatus = 0x8000000200046000
kernel (physical): 0000000080200000..0000000085cf7418
kernel (remapped): ffffffff00200000..ffffffff05cf7418
device tree:       00000000ff6e1000..00000000ff6e6000



panic cpu=1


panicked at 'called `Option::unwrap()` on a `None` value', zCore/src/handler.rs:22:19
[ 34.208971 ERROR 1 0:0 zcore::lang]

panicked at 'called `Option::unwrap()` on a `None` value', zCore/src/handler.rs:22:19
```

---

现在修改了链接位置、硬编码了构造启动页表、关闭了多核启动

**Comment by YdrMaster** [comment]
重做了启动映射解决了这个问题，现在串口驱动不行

**Comment by YdrMaster** [comment]
启动成功
